import fs from 'fs'
import path from 'path'

const envPath = path.join(process.cwd(), '.env')
const exists = fs.existsSync(envPath)

if (exists) {
  const content = fs.readFileSync(envPath, 'utf8')
  if (/^DATABASE_URL=/m.test(content)) {
    console.log('.env already has DATABASE_URL; leaving as-is')
    process.exit(0)
  }
}

const user = process.env.USER || process.env.LOGNAME || 'postgres'
const url = `postgresql://${user}@localhost:5432/health?schema=public`
const out = `# Auto-generated by env:setup\nDATABASE_URL="${url}"\n`

fs.writeFileSync(envPath, out, 'utf8')
console.log(`Wrote ${envPath} with DATABASE_URL=${url}`)

